name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: test
        run: pip install tox && tox
